# Generated by Django 5.2.1 on 2025-06-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_paciente_foto_alter_fotopaciente_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
    ]
