# Generated by Django 5.2.1 on 2025-06-21 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Atención')),
                ('hora', models.TimeField(verbose_name='Hora de Atención')),
                ('paciente', models.CharField(max_length=100, verbose_name='Paciente')),
                ('doctor', models.CharField(max_length=100, verbose_name='Doctor')),
                ('motivo_consulta', models.TextField(blank=True, null=True, verbose_name='Motivo de Consulta')),
            ],
            options={
                'verbose_name': 'Atención Médica',
                'verbose_name_plural': 'Atenciones Médicas',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='CitasMedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField(verbose_name='Fecha de Cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de Cita')),
                ('paciente', models.CharField(max_length=100, verbose_name='Paciente')),
                ('doctor', models.CharField(max_length=100, verbose_name='Doctor')),
                ('motivo_cita', models.TextField(blank=True, null=True, verbose_name='Motivo de Cita')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['fecha_cita', 'hora_cita'],
            },
        ),
        migrations.CreateModel(
            name='HorariosAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=10, verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('doctor', models.CharField(max_length=100, verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'ordering': ['dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('dia_semana', 'hora_inicio', 'doctor'), name='unique_horario_atencion')],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('paciente', models.CharField(max_length=100, verbose_name='Paciente')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_pago'],
                'constraints': [models.UniqueConstraint(fields=('fecha_pago', 'paciente'), name='unique_fecha_paciente')],
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='doctor.pagos', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'ordering': ['pago', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ServiciosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
                'ordering': ['nombre_servicio'],
                'constraints': [models.UniqueConstraint(fields=('nombre_servicio',), name='unique_nombre_servicio')],
            },
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
