# Generated by Django 5.2.1 on 2025-06-21 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_doctor_options'),
        ('doctor', '0002_atencionmedica_citasmedicas_horariosatencion_pagos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionmedica',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='atencionmedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente'),
        ),
    ]
