# Generated by Django 5.2.1 on 2025-06-21 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_doctor_options'),
        ('doctor', '0004_alter_citasmedicas_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente'),
        ),
    ]
