# Generated by Django 5.2.1 on 2025-06-21 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_doctor_options'),
        ('doctor', '0005_alter_pagos_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosatencion',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Doctor'),
        ),
    ]
